### ISSUE TITLE
InitializationError: docker-credential-gcloud not installed or not available in PATH

### ISSUE THREAD

**Issue by felipebueno** [jayfk/launchr#22]
Hi!

This error shows up when I run ```docker-compose up```

```
Building app
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.22.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 71, in main
    command()
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 127, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1052, in up
    to_attach = up(False)
  File "/usr/lib/python3.7/site-packages/compose/cli/main.py", line 1048, in up
    silent=options.get('--quiet-pull'),
  File "/usr/lib/python3.7/site-packages/compose/project.py", line 471, in up
    svc.ensure_image_exists(do_build=do_build, silent=silent)
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 352, in ensure_image_exists
    self.build()
  File "/usr/lib/python3.7/site-packages/compose/service.py", line 1067, in build
    platform=self.platform,
  File "/usr/lib/python3.7/site-packages/docker/api/build.py", line 251, in build
    self._set_auth_headers(headers)
  File "/usr/lib/python3.7/site-packages/docker/api/build.py", line 313, in _set_auth_headers
    credstore_env=self.credstore_env
  File "/usr/lib/python3.7/site-packages/docker/auth.py", line 96, in resolve_authconfig
    authconfig, registry, store_name, env=credstore_env
  File "/usr/lib/python3.7/site-packages/docker/auth.py", line 127, in _resolve_authconfig_credstore
    store = dockerpycreds.Store(credstore_name, environment=env)
  File "/usr/lib/python3.7/site-packages/dockerpycreds/store.py", line 25, in __init__
    self.program
dockerpycreds.errors.InitializationError: docker-credential-gcloud not installed or not available in PATH
```

**Comment by felipebueno** [comment]
My bad :sweat_smile: 

https://superuser.com/a/1411019/82641
